### ISSUE TITLE
You must specify a non-null value for the Body or SourceFile parameters.

### ISSUE THREAD

**Issue by nciske** [paulsenag/paulsen-gforms-s3-uploads#1]
Just found your plugin and it's a life saver... except that it throws a fatal error on submit.

Using multi-upload field (with 3 files).
Form ID and Field ID are correct.

Host is Media Temple Grid Service (if that matters).

Any ideas?

[20-Jan-2015 17:31:12 UTC] PHP Fatal error:  Uncaught exception 'Aws\Common\Exception\InvalidArgumentException' with message 'You must specify a non-null value for the Body or SourceFile parameters.' in /html/wp-content/plugins/gforms-s3-uploads/vendor/aws/aws-sdk-php/src/Aws/Common/Client/UploadBodyListener.php:91

Stack trace:

#0 [internal function]: Aws\Common\Client\UploadBodyListener->onCommandBeforePrepare(Object(Guzzle\Common\Event), 'command.before_...', Object(Symfony\Component\EventDispatcher\EventDispatcher))

#1 /html/wp-content/plugins/gforms-s3-uploads/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'command.before_...', Object(Symfony\Component\EventDispatcher\EventDispatcher))

#2 /html/wp-content/plugins/gforms-s3-uploads/vendor/symfony/event-dispat in /html/wp-content/plugins/gforms-s3-uploads/vendor/aws/aws-sdk-php/src/Aws/Common/Client/UploadBodyListener.php on line 91

**Comment by oclupaca** [comment]
@nciske - We hadn't taken the multi upload option into account. We just pushed out an update enabling multiple uploads. Can you give it a try?

FYI, our replies could be sporadic, but we'll do our best to help out.

**Comment by nciske** [comment]
That fixed it, thanks for the quick reply!

**Comment by harissarwar** [comment]
i have the same issue while uploading images on s3.


use Aws\S3\S3Client;

// Instantiate the client.
$s3Client = S3Client::factory(array(
    'key'    => 'xxxxxxxxxxxxxx',
    'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'region' => 'us-east-1'
 ));

$ext = pathinfo($_FILES['company_logo']['name'], PATHINFO_EXTENSION);
$randomFilename = md5($_FILES['company_logo']['name'] . time()) . '.' . strtolower($ext);
    move_uploaded_file($_FILES['company_logo']['tmp_name'], ROOT .'assets/img/' . $randomFilename);


    // Upload a file.
    $filePath =  ROOT.'assets/img/'. $randomFilename;
    $result = $s3Client->putObject(array(
            'Bucket'       => $bucket,
            'Key'          => $randomFilename,
            'SourceFile'   => $filePath,
            'ACL'          => 'public-read',
            'StorageClass' => 'REDUCED_REDUNDANCY',

    ));

can any body tell me where i am doing wrong in this.
