### ISSUE TITLE
Files are not deleted after upload?

### ISSUE THREAD

**Issue by nciske** [paulsenag/paulsen-gforms-s3-uploads#3]
Not sure if this is a bug or a setting I'm missing? I don't see any code related to it so it may be a feature request ;-)

While files are now going to S3 as expected, they remain on my WP install as well.

**Comment by schoffelman** [comment]
I believe they'll stay on the WP install. One of the future feature requests is to integrate with the wp-amazon-web-services plugin, which I believe has that as an option.

**Comment by nciske** [comment]
OK, noted. I may see if I can get something working in the meantime and submit a pull request.

**Comment by schoffelman** [comment]
Sounds great - thanks @nciske
